WITH country_counts AS (
  SELECT
    COUNTRY,
    COUNT(DISTINCT COMPETITOR) AS COMPETITORS
  FROM playground.foreign_competitors
  GROUP BY COUNTRY
)
(SELECT COUNTRY, COMPETITORS
FROM country_counts
ORDER BY COMPETITORS ASC, COUNTRY ASC)

UNION ALL

(SELECT 'Total:' AS COUNTRY, SUM(COMPETITORS)
FROM country_counts)
